### PR TITLE
fix pvalue and pvalue-downsample plot space at the top of the figure

### LINKED ISSUE #76: plot.pvalue() add back space above for text
since #53 plot.pvalue levels are missing "" on top of y axis ticks, so text difficult to read sometimes.

Image

@EngineerDanny can you please submit a PR to fix? add this logic back:
```r
  levs.present <- c(
    "same",
    measure.vars,
    paste0(measure.vars,"-same"))
  levs.possible <- c(
    "all",
    "all-same",
    "same",
    "other-same",
    "other")
  levs <- c(
    levs.possible[levs.possible %in% levs.present],
    "")#for space above.
```

### PR DESCRIPTION
**Pull request by EngineerDanny**
Add the vertical space at the top of the figure.
Fix #76 

pvalue_downsample_tmp_plot

### CODE REVIEW

**Comment by tdhock** [comment]
[Preview](https://84-merge--mlr3resampling.netlify.app)

File: R/pvalue.R [hunk 1]
```diff
@@ -51,7 +51,7 @@ pvalue_compute <- function(
     score_value$Train_subsets,
     paste0(measure.vars, "-same")
   ))
-  label_order <- canonical_levels[canonical_levels %in% present_levels]
+  label_order <- c(canonical_levels[canonical_levels %in% present_levels], "")
```
Comment (tdhock) [inline R/pvalue.R]:
```suggestion
  label_order <- c(intersect(canonical_levels, present_levels), "")
```
